name: FTP Deploy
on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:
jobs:
  ftp-deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp://e150555-ftp.services.easyname.eu  # Your FTP server
          username: ${{ secrets.FTP_USERNAME }}  # Set in your repo secrets
          password: ${{ secrets.FTP_PASSWORD }}  # Set in your repo secrets
          local-dir: ./  # The local directory (or build directory if you have a build step)
          remote-dir: /html/webroot/konferenz_website  # The target directory on your FTP server
